[package]
name = "aprs-logger"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8", features = [ "runtime-tokio", "tls-native-tls" ] }
tokio = { version = "1.42.0", features = ["full"] }
futures = "0.3"